### ISSUE TITLE
The given example doesn't work.

### ISSUE THREAD

**Issue by arbhassan** [scriptix-io/realtime-examples#2]
Hi there!

the example given in the client.py files return an EOF error.

`curl -s  http://icecast-bnr.cdp.triple-it.nl/bnr_mp3_96_06 |\
       ffmpeg -loglevel panic -i - -ac 1 -acodec pcm_s16le -ar 16000 -f wav - |\
       python3.7 client.py nl-nl token`

first the livestream above returned a 404 error then i changed it with another stream but still i'm getting EOF.

Running the server by only using `python client.py nl-nl token` works fine though.

any help would be greatly appreciated. 

Thanks!

Arbab Hassan

**Comment by olegtaranenko** [comment]
I running the same issue out. Could you replace the outdated input stream with the actual one?

**Comment by arbhassan** [comment]
@blokje sorry to ping you here. could you help us out?

**Comment by blokje** [comment]
Hi @arbhassan 

The url in the example doesn't exist anymore  you could use a different one and it should work as is. 

You could try the following URL https://stream.bnr.nl/bnr_mp3_128_20 otherwise feel free to contact me by mail (rick@scriptix.io)

**Comment by arbhassan** [comment]
Hi @blokje Rick!

Thanks for responding.

I just checked it with the new URL you sent but still the same error.

`Server is listening
{"state":"listening","session_id":"e509e9190007f50009bc408976"}
EOF
{"state":"stopped"}
Stopped
`

**Comment by arbhassan** [comment]
Here's the curl command i'm using.

`curl -s  https://stream.bnr.nl/bnr_mp3_128_20  |\
                                                                       ffmpeg -loglevel panic -i - -ac 1 -acodec pcm_s16le -ar 16000 -f wav - |\
                                                                       python client.py en-us token
`

**Comment by arbhassan** [comment]
Okay! the link was redirecting to another link. so that's why it was giving error. 

Solved Now! 

Thanks!!!!

**Comment by olegtaranenko** [comment]
`curl -s https://22533.live.streamtheworld.com/BNR_NIEUWSRADIO.mp3?dist=other | ffmpeg -loglevel panic -i - -ac 1 -acodec pcm_s16le -ar 16000 -f wav - | python client.py nl-nl <token>`
is the correct link

**Comment by blokje** [comment]
@arbhassan @olegtaranenko Sorry for the late response. But this also worked for me just now:

```bash
ffmpeg -loglevel panic -i   https://stream.bnr.nl/bnr_mp3_128_20  -ac 1 -acodec pcm_s16le -ar 16000 -f wav - | python client.py nl-nl <token>
```

I cannot remember why the curl was involved in the original example, with a modern FFMpeg this obviously not a requirement.

I've updated the example: https://github.com/scriptix-io/realtime-examples/blob/master/python-websockets/client.py#L5
